"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InitializableClones__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "address",
                name: "instance",
                type: "address",
            },
        ],
        name: "Deployed",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "master",
                type: "address",
            },
            {
                internalType: "bytes",
                name: "initializer",
                type: "bytes",
            },
        ],
        name: "clone",
        outputs: [
            {
                internalType: "address",
                name: "instance",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class InitializableClones__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.InitializableClones__factory = InitializableClones__factory;
InitializableClones__factory.abi = _abi;
